### PR TITLE
suggested implementation to add helptext

### PR DESCRIPTION
**Pull request by rawdlite**
in the support forum the advice to call dsptoolkit -h is frequently mentioned.
Yet the output is very limited giving only function names. A description of what the function does and what parameters are allowed is missing.
This is a proposal for a more verbose help output.

Alternatively or in addition to a brief output of only the most important commands a --doc option could be added to provide a more in depth documentation.

### CODE REVIEW

**Comment by hifiberry** [comment]
You added command that do not exist like "tone-control" or "adjust-volume". Did you check the available commands in dsptoolkit.py? You can find the supported commands here:
https://github.com/hifiberry/hifiberry-dsp/blob/3384c0cd26088a1c784942c9e23f1f5ca3cd25fb/hifiberrydsp/dsptoolkit.py#L385

**Comment by rawdlite** [comment]
1. The text is only an example showing how help text could be impleneted.
2. tone-control is on line 409
            "tone-control": self.cmd_tonecontrol,
            
           i am already using this command on my system.

**Comment by rawdlite** [comment]
"adjust-volume": self.cmd_adjust_volume,
          
on line 392. Only 7 lines down from your link. ;-)

**Comment by rawdlite** [comment]
Added help for the most important commands (tbd)
Please review.

**Pull request merged**
